name = "protobin"
version = "1.1.0"

description = "Decode the protobuf wire format."
licences = ["Apache-2.0"]
repository = { type = "github", user = "gavinmorrow", repo = "protobin" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
